<a href="https://colab.research.google.com/github/Dharaneesh8/Learning_Journey/blob/main/Pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.DataFrame({
    "Name":["Arun","Bala","Chandra","Daredevil","Eoin","Faf"],
    "Age":[20,23,22,21,23,22],
    "Mark":[80,78,92,90,88,83]
})

In [ ]:
print(df)

        Name  Age  Mark
0       Arun   20    80
1       Bala   23    78
2    Chandra   22    92
3  Daredevil   21    90
4       Eoin   23    88
5        Faf   22    83

In [ ]:
df.head()

        Name  Age  Mark
0       Arun   20    80
1       Bala   23    78
2    Chandra   22    92
3  Daredevil   21    90
4       Eoin   23    88

In [ ]:
df.shape

(6, 3)

In [ ]:
df.columns

Index(['Name', 'Age', 'Mark'], dtype='object')

In [ ]:
df[["Name","Age"]]

        Name  Age
0       Arun   20
1       Bala   23
2    Chandra   22
3  Daredevil   21
4       Eoin   23
5        Faf   22

In [ ]:
df[["Age"]]

   Age
0   20
1   23
2   22
3   21
4   23
5   22

In [ ]:
df.iloc[0:3,2]

0    80
1    78
2    92
Name: Mark, dtype: int64

In [ ]:
df.loc[0:3,["Name","Mark"]]

        Name  Mark
0       Arun    80
1       Bala    78
2    Chandra    92
3  Daredevil    90

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     6 non-null      int64
 2   Mark    6 non-null      int64
dtypes: int64(2), object(1)
memory usage: 276.0+ bytes

In [ ]:
df[df["Mark"]>90]

      Name  Age  Mark
2  Chandra   22    92

In [ ]:
df['Mark']>90

0    False
1    False
2     True
3    False
4    False
5    False
Name: Mark, dtype: bool

In [ ]:
df[(df["Mark"]>=90) | (df['Age']<22)]

        Name  Age  Mark
0       Arun   20    80
2    Chandra   22    92
3  Daredevil   21    90

In [ ]:
df["Bonus"]=df["Mark"]+2
print(df)

        Name  Age  Mark  Bonus
0       Arun   20    80     82
1       Bala   23    78     80
2    Chandra   22    92     94
3  Daredevil   21    90     92
4       Eoin   23    88     90
5        Faf   22    83     85

In [ ]:
df["Category"]=np.where(
    df['Mark']>=90,
    "Topper",
    "Average"
)
print(df)

        Name  Age  Mark  Bonus Category
0       Arun   20    80     82  Average
1       Bala   23    78     80  Average
2    Chandra   22    92     94   Topper
3  Daredevil   21    90     92   Topper
4       Eoin   23    88     90  Average
5        Faf   22    83     85  Average

In [ ]:
maja = pd.DataFrame({
    "Name": ["A", "B", "C", "D", "E"],
    "Age": [20, np.nan, 30, 25, np.nan],
    "Salary": [30000, 40000, np.nan, 50000, 60000]
})

NameError: name 'pd' is not defined

In [ ]:
df1 = pd.DataFrame({
    "Name": ["A", "B"],
    "Age": [20, 25]
})

df2 = pd.DataFrame({
    "Name": ["C", "D"],
    "Age": [30, 35]
})

In [ ]:
pd.concat([df1, df2],ignore_index=True, axis=0)

  Name  Age
0    A   20
1    B   25
2    C   30
3    D   35

In [ ]:
hi= pd.DataFrame({
    "Name": ["A", "B", "C", "B","A"],
    "Age": [20, 25, 30, 25,20]
})

In [ ]:
hi.duplicated().sum()

np.int64(2)

In [ ]:
hi.drop_duplicates()

  Name  Age
0    A   20
1    B   25
2    C   30

In [ ]:
df = pd.DataFrame({
    "Age": ["20", "25", "30"],
    "Salary": ["30000", "40000", "50000"]
})

In [ ]:
df["Age"].dtypes

dtype('O')

In [ ]:
df["Age"]=df["Age"].astype(int)

In [ ]:
import pandas as pd

# 1. Create a sample DataFrame
data = {
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Department": ["Sales", "Engineering", "Sales", "Engineering", "Engineering"],
    "Salary": [60000, 80000, 70000, 95000, 65000]
}
df = pd.DataFrame(data)

# 2. Apply your transform code
df["Dept_Avg_Salary"] = df.groupby("Department")["Salary"].transform("mean")

print(df)

  Employee   Department  Salary  Dept_Avg_Salary
0    Alice        Sales   60000          65000.0
1      Bob  Engineering   80000          80000.0
2  Charlie        Sales   70000          65000.0
3    David  Engineering   95000          80000.0
4      Eva  Engineering   65000          80000.0

In [ ]:

df["Dept_Avg_Salary"] = df.groupby("Department")["Salary"].mean()
print(df)

  Employee   Department  Salary  Dept_Avg_Salary
0    Alice        Sales   60000              NaN
1      Bob  Engineering   80000              NaN
2  Charlie        Sales   70000              NaN
3    David  Engineering   95000              NaN
4      Eva  Engineering   65000              NaN

In [ ]:
import pandas as pd

# 1. Create a sample DataFrame
data = {
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Department": ["Sales", "Engineering", "Sales", "Engineering", "Engineering"],
    "Salary": [45000, 80000, 40000, 95000, 65000],
    "Age": [20,30,50,22,33]
}
df = pd.DataFrame(data)

result=df.groupby("Department").filter(
    lambda x:x["Salary"].mean()>50000
)
print(result)

  Employee   Department  Salary  Age
1      Bob  Engineering   80000   30
3    David  Engineering   95000   22
4      Eva  Engineering   65000   33

In [ ]:
df["Age_Groups"]=pd.cut(
    df["Age"],
    bins=[0,25,45,70],
    labels=["Young","Adult","Senior Citizen"]
)
print(df)

  Employee   Department  Salary  Age      Age_Groups
0    Alice        Sales   45000   20           Young
1      Bob  Engineering   80000   30           Adult
2  Charlie        Sales   40000   50  Senior Citizen
3    David  Engineering   95000   22           Young
4      Eva  Engineering   65000   33           Adult

In [ ]:
df["Package"]=pd.qcut(
    df["Salary"],
    q=2,
    labels=["low","high"]
)
print(df)

  Employee   Department  Salary  Age      Age_Groups Package
0    Alice        Sales   45000   20           Young     low
1      Bob  Engineering   80000   30           Adult    high
2  Charlie        Sales   40000   50  Senior Citizen     low
3    David  Engineering   95000   22           Young    high
4      Eva  Engineering   65000   33           Adult     low

In [ ]:
import pandas as pd

df=pd.DataFrame({
    "Dept":["IT","HR","HR","IT"],
    "Salary":[45000,50000,20000,40000],
    "Year":[2024,2025,2024,2025]
})

res=df.groupby(["Dept","Year"])["Salary"].mean()
print(res)

Dept  Year
HR    2024    20000.0
      2025    50000.0
IT    2024    45000.0
      2025    40000.0
Name: Salary, dtype: float64

In [ ]:
poda=res.unstack()
print(poda)

vada=poda.stack()
print(vada)

Year     2024     2025
Dept
HR    20000.0  50000.0
IT    45000.0  40000.0
Dept  Year
HR    2024    20000.0
      2025    50000.0
IT    2024    45000.0
      2025    40000.0
dtype: float64

In [ ]:
poda=res.unstack(level="Dept")
print(poda)

Dept       HR       IT
Year
2024  20000.0  45000.0
2025  50000.0  40000.0

In [ ]:
df1 = pd.DataFrame({
    "Employee_ID": [1, 2, 3, 4],
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Department": ["HR", "Engineering", "Sales", "HR"]
})

df2 = pd.DataFrame({
    "Employee_ID": [3, 4, 5, 6],
    "Salary": [70000, 95000, 60000, 85000],
    "Project": ["Alpha", "Beta", "Gamma", "Delta"]
})

result = pd.merge(
    df1,
    df2,
    on="Employee_ID",
    how="outer",
    indicator=True
)
print(result)

   Employee_ID     Name   Department   Salary Project      _merge
0            1    Alice           HR      NaN     NaN   left_only
1            2      Bob  Engineering      NaN     NaN   left_only
2            3  Charlie        Sales  70000.0   Alpha        both
3            4    David           HR  95000.0    Beta        both
4            5      NaN          NaN  60000.0   Gamma  right_only
5            6      NaN          NaN  85000.0   Delta  right_only

In [ ]:
result[result["_merge"] == "left_only"]

   Employee_ID   Name   Department  Salary Project     _merge
0            1  Alice           HR     NaN     NaN  left_only
1            2    Bob  Engineering     NaN     NaN  left_only

In [ ]:
import pandas as pd

# Define df to ensure it's available for the Excel operations
data = {
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Department": ["Sales", "Engineering", "Sales", "Engineering", "Engineering"],
    "Salary": [45000, 80000, 40000, 95000, 65000],
    "Age": [20,30,50,22,33]
}
df = pd.DataFrame(data)

with pd.ExcelWriter("employee_report.xlsx") as writer:
    df.to_excel(writer, sheet_name="Employees", index=False)
    df.groupby("Department")["Salary"].mean().to_excel(
        writer,
        sheet_name="Department_Salary"
    )

In [ ]:
with pd.ExcelWriter("employee_xlsx") as writer:
  df.to_excel()

_IncompleteInputError: incomplete input (2477831621.py, line 1)